// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreateGeoObjectInput struct {
	Type       string                 `json:"type"`
	Title      string                 `json:"title"`
	Content    *string                `json:"content,omitempty"`
	ImageURL   *string                `json:"imageUrl,omitempty"`
	Properties map[string]interface{} `json:"properties,omitempty"`
	Lat        float64                `json:"lat"`
	Lng        float64                `json:"lng"`
}

type CreateSketchInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateUploadInput struct {
	Type FileType `json:"type"`
	URL  string   `json:"url"`
}

type GenshinCharater struct {
	ActivedConstellationNum int            `json:"actived_constellation_num"`
	Element                 string         `json:"element"`
	Level                   int            `json:"level"`
	Name                    string         `json:"name"`
	Rarity                  int            `json:"rarity"`
	Weapon                  *GenshinWeapon `json:"weapon"`
}

type GenshinWeapon struct {
	Level  int    `json:"level"`
	Name   string `json:"name"`
	Rarity int    `json:"rarity"`
}

type GeoObject struct {
	ID         int                    `json:"id"`
	Type       string                 `json:"type"`
	Title      string                 `json:"title"`
	Content    *string                `json:"content,omitempty"`
	ImageURL   *string                `json:"imageUrl,omitempty"`
	Properties map[string]interface{} `json:"properties,omitempty"`
	Lat        float64                `json:"lat"`
	Lng        float64                `json:"lng"`
	CreatedAt  time.Time              `json:"createdAt"`
	UpdatedAt  time.Time              `json:"updatedAt"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Session struct {
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Token     string    `json:"token"`
	UserID    int       `json:"userId"`
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type Sketch struct {
	ID        int       `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	UserID    int       `json:"userID"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type UpdateGeoObjectInput struct {
	ID         int                    `json:"id"`
	Type       string                 `json:"type"`
	Title      string                 `json:"title"`
	Content    *string                `json:"content,omitempty"`
	ImageURL   *string                `json:"imageUrl,omitempty"`
	Properties map[string]interface{} `json:"properties,omitempty"`
	Lat        float64                `json:"lat"`
	Lng        float64                `json:"lng"`
}

type UpdateSketchInput struct {
	ID      int    `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Upload struct {
	ID   int      `json:"id"`
	Type FileType `json:"type"`
	URL  string   `json:"url"`
}

type User struct {
	ID        int       `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type FileType string

const (
	FileTypeJSON  FileType = "JSON"
	FileTypeImage FileType = "IMAGE"
	FileTypeOther FileType = "OTHER"
)

var AllFileType = []FileType{
	FileTypeJSON,
	FileTypeImage,
	FileTypeOther,
}

func (e FileType) IsValid() bool {
	switch e {
	case FileTypeJSON, FileTypeImage, FileTypeOther:
		return true
	}
	return false
}

func (e FileType) String() string {
	return string(e)
}

func (e *FileType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FileType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FileType", str)
	}
	return nil
}

func (e FileType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
