// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GenshinCharater struct {
	ActivedConstellationNum int            `json:"actived_constellation_num"`
	Element                 string         `json:"element"`
	Level                   int            `json:"level"`
	Name                    string         `json:"name"`
	Rarity                  int            `json:"rarity"`
	Weapon                  *GenshinWeapon `json:"weapon"`
}

type GenshinWeapon struct {
	Level  int    `json:"level"`
	Name   string `json:"name"`
	Rarity int    `json:"rarity"`
}
